spring.application.name=music-recommender

spring.datasource.url=jdbc:postgresql://db.byayrdwyakydforaglxr.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Contraseña123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=patriciopmontane05@gmail.com
spring.mail.password=lnaq tjyu apyi jrnn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.upload.dir=uploads

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=${PORT:8080}